command = "cp"

[[match_err]]
pattern = [
	"-r not specified",
]
suggest = [
'''
{{command[0]}} -r {{command[1:]}} '''
]

[[match_err]]
pattern = [
	"cannot create directory",
]
suggest = [
'''
#[err_contains(no such file or directory)]
mkdir -p {{cmd::(?m)\s(\S+[\\\/])\S*\s*$}} && \
{{command[0]}} {{opt::\s(-[\w]+)}} {{command[1:]}} '''
]

