command = "cd"

[[match_err]]
pattern = [
	"no such file or directory",
	"does not exist"
]
suggest = [
'''
#[!shell(nu)]
mkdir --parents {{command[1]}} && \
cd {{command[1]}} '''
]

[[match_err]]
pattern = [
	"nu::shell::directory_not_found"
]
suggest = [
'''
mkdir {{command[1]}} and \
cd {{command[1]}} '''
]
