command = "jj"

[[match_err]]
pattern = [
	"pass `--ignore-immutable`"
]
suggest = [
'''
{{command}} --ignore-immutable'''
]

[[match_err]]
pattern = [
	"use --allow-new to push new bookmark"
]
suggest = [
'''
{{command}} --allow-new'''
]

[[match_err]]
pattern = [
	"no bookmarks found in the default push revset"
]
suggest = [
'''
{{command}} --change @'''
]

[[match_err]]
pattern = [
	"hint: run `",
	"and try again",
]
suggest = [
'''
#[
  err_contains(hint: run `),
  err_contains(and try again)
]
{{err::(?:hint: run `)(.*)(?:` and try again.)}}'''
]
