command = "_PR_general"

[[match_err]]
pattern = [
	"command not found",
	"unknown command",
	"nu::shell::external_command",
	"is not recognized as a name of a cmdlet"
]
suggest = [
'''
{{select[0](path)}} {{command[1:]}} '''
]

[[match_err]]
pattern = [
	"permission denied",
	"is not an executable file"
]
suggest = [
'''
#[exe_contains(/)]
chmod +x {{command[0]}} &&
{{command}}'''
]
