command = "privilege"

[[match_err]]
pattern = [
	"as root",
	"authentication is required",
	"be root",
	"be superuser",
	"eacces",
	"edspermissionerror",
	"error: insufficient privileges",
	"insufficient privileges",
	"need root",
	"non-root users cannot",
	"not super-user",
	"only root can",
	"operation not permitted",
	"permission denied",
	"requires root",
	"root privilege",
	"root user",
	"sudorequirederror",
	"superuser privilege",
	"unless you are root",
	"updatedb: can not open a temporary file",
	"use `sudo`",
	"you don't have access to the history db.",
	"you don't have write permissions"
]
suggest = [
'''
#[executable(sudo)]
sudo {{command}} ''',
'''
#[executable(doas)]
doas {{command}} '''
]
